// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY1X8Nt8CsrPypCkKlXA9gvn9b8sesRh0',
    appId: '1:947532662145:web:99287632c76544e0fa1480',
    messagingSenderId: '947532662145',
    projectId: 'mocha-app-bad3f',
    authDomain: 'mocha-app-bad3f.firebaseapp.com',
    storageBucket: 'mocha-app-bad3f.firebasestorage.app',
    measurementId: 'G-XQCNGVWDMB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFafBASxoVvZpUAMu_0LOJWQ3Gb3rG5M4',
    appId: '1:947532662145:android:eb76ca8ba495b99ffa1480',
    messagingSenderId: '947532662145',
    projectId: 'mocha-app-bad3f',
    storageBucket: 'mocha-app-bad3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLYplU3aWfpSHzVnjN_y_PXe9NYU2squ8',
    appId: '1:947532662145:ios:c6a75624f62e4960fa1480',
    messagingSenderId: '947532662145',
    projectId: 'mocha-app-bad3f',
    storageBucket: 'mocha-app-bad3f.firebasestorage.app',
    iosBundleId: 'uth.edu.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLYplU3aWfpSHzVnjN_y_PXe9NYU2squ8',
    appId: '1:947532662145:ios:c6a75624f62e4960fa1480',
    messagingSenderId: '947532662145',
    projectId: 'mocha-app-bad3f',
    storageBucket: 'mocha-app-bad3f.firebasestorage.app',
    iosBundleId: 'uth.edu.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAY1X8Nt8CsrPypCkKlXA9gvn9b8sesRh0',
    appId: '1:947532662145:web:6d5f13836d4e32fafa1480',
    messagingSenderId: '947532662145',
    projectId: 'mocha-app-bad3f',
    authDomain: 'mocha-app-bad3f.firebaseapp.com',
    storageBucket: 'mocha-app-bad3f.firebasestorage.app',
    measurementId: 'G-W22YX4W44Q',
  );
}
