name: CI Test (Flutter + Spring Boot)

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main, develop ]

jobs:
  flutter_test:
    name: Test Flutter App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.6'  # thay bằng version bạn đang dùng

      - name: Get dependencies
        working-directory: frontend
        run: flutter pub get

      - name: Analyze Flutter code
        working-directory: frontend
        run: flutter analyze

      - name: Run Flutter tests
        working-directory: frontend
        run: flutter test

  spring_test:
    name: Test Spring Boot Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build & test backend
        working-directory: backend
        run: ./mvnw clean test
