name: Flutter CI Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main, develop ]

jobs:
  flutter_test:
    name: Flutter Frontend CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.6' 

      - name: Get dependencies
        working-directory: frontend
        run: flutter pub get

      - name: Analyze Flutter code
        working-directory: frontend
        run: flutter analyze

      # - name: Run Flutter tests
      #   working-directory: frontend
      #   run: flutter test

      - name: ✅ CI Status
        run: echo "✅ Flutter CI passed successfully!"
